ALLOWED_HOSTS = ("*",)

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

CSRF_TRUSTED_ORIGINS = ("http://localhost:3000/",)

# CORS_REPLACE_HTTPS_REFERER = True

CORS_ORIGIN_WHITELIST = ("http://localhost:3000",)
